use_frameworks!

platform :ios, '8.0'

target 'LLPresentationController_Example' do
  pod 'LLPresentationController', :path => '../'

  target 'LLPresentationController_Tests' do
    inherit! :search_paths

    
  end
end
